### ISSUE TITLE
Zip files are corrupted

### ISSUE THREAD

**Issue by giuliomoro** [echapmanFromBunnings/upload-release-assets#4]
This workflow:

```
    - name: Upload assets to existing release by tag
      uses: echapmanFromBunnings/upload-release-assets@1.4
      with:
        releaseTag: dev-release
        githubToken: ${{ github.token }}
        files: |
          dist/myfile.zip
```
results in a corrupted zip file, even though `dist/myfile.zip` is a valid zip archive.

This may be down to utf8 being used to read all files https://github.com/echapmanFromBunnings/upload-release-assets/blob/main/action.yml#L130
